global:
  scrape_interval: 5s

scrape_configs:
  - job_name: server-linux # Job
    static_configs:
      - targets:
      # list instance
        - "localhost:9100"
  - job_name: prometheus-itself
    static_configs:
      - targets:
        - localhost:9090