global:
  scrape_interval: 5s

scrape_configs:
  - job_name: server-linux-via-dns
    dns_sd_configs: # dns service discovery
      - names:
          - prom-target.rahadian.dev
        type: A
        port: 9100
  - job_name: prometheus-itself
    static_configs:
      - targets:
        - localhost:9090