apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: review-destionationrule
  namespace: belajar-istio
spec:
  host: review.belajar-istio.svc.cluster.local
  subsets:
  - name: versi-1-0-0 # DNS-1123 label naming conventions
    labels:
      version: 1.0.0
  - name: versi-2-0-0 # DNS-1123 label naming conventions
    labels:
      version: 2.0.0