# Default values for my-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: rahadiangg/demo-istio
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: review-svc-3.0.0

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 64m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# env variable
env:
  # aaa: bbb
